#!/bin/sh

## hyphop ##

# simple automate ssh shell access for mizy

DEV=usb0

[ "$DEVIP" ] || DEVIP=$(cat /tmp/mizy_usb_ip 2>/dev/null)
[ "$DEVIP" ] || {
    for DEVIP in $(ip -4 addr show $DEV | grep -m1 -o -P \\d\+\.\\d\+\.\\d\+\.\\d\+); do
	break
    done
}

CONF=$(dirname $0)/../share/ssh.config

echo "[i] mizy usb ip: $DEVIP" >&2

echo "# ssh -F $CONF root@$DEVIP">&2

ssh -q -F $CONF root@$DEVIP
